"""Build `reference/` from a run that has already happened.

A cloner should be able to see what a session produces before spending anything. That
is what this directory is for, and it is the reason the old `results/reference/` existed
— it was deleted because it held measurements of models this build no longer contains,
which is a reference to a system that does not exist.

**So it is GENERATED, from results/ on disk, and never hand-assembled.** The same
argument as the starter branch: a hand-maintained artefact is correct for about a week
and then describes something else.

    uv run python scripts/build_reference.py --note "dress rehearsal, presenting machine"

WHAT IT MUST CARRY, AND WHY EACH

Every figure in here is a measurement taken on one day, on one account, against one
gold set. Somebody will read it as what they should expect, so each of those has to
travel with the number rather than sit in a caption:

    date      a rate limit, a served snapshot and a price table all move
    models    the served ids, not the requested ones
    profile   the item count and the arms are properties of it
    n         every figure this project draws carries its own
    tier      throughput and rate limits are account-dependent, and the timings here
              are the honest output of ONE account rather than a promise

NOTHING UNDER `src/loopeng/` MAY IMPORT THIS. It is documentation, not a data source —
that is the structural difference from the directory that was deleted, and a test
asserts it.
"""

import argparse
import json
import shutil
import sys
from datetime import date
from pathlib import Path

from loopeng.registry import REGISTRY, spec_for
from loopeng.sweep.endings import select
from loopeng.sweep.experiments import ARM_ORDER, load_arms
from loopeng.sweep.orchestrator import load_all

OUT = Path("reference")


def _served(arms: dict[str, dict]) -> dict[str, str]:
    """The model ids as the API actually served them, per role, from the arms."""
    served = {}
    for role in sorted(REGISTRY):
        served[role] = spec_for(role).model_id
    return served


def summary_table(arms: dict[str, dict], cells: list[dict]) -> str:
    lines = [
        "| arm | model | level | loops | n | correct | silent | visible | abstained "
        "| unearned | est. cost |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for name in ARM_ORDER + ("trap-reference-L0",):
        arm = arms.get(name)
        if arm is None:
            continue
        bands = arm["bands"]
        lines.append(
            f"| `{name}` | {spec_for(arm['role']).model_id} | {arm['level']} "
            f"| {arm['loops']} | {arm['n_items']} | {bands['correct']} "
            f"| {bands['wrong_and_silent']} | {bands['wrong_and_caught']} "
            f"| {bands['abstained']} | {bands['unearned']} "
            f"| est. ${arm['cost_usd']['value']:.4f} |"
        )
    return "\n".join(lines)


def build(note: str, tier: str, out: Path = OUT) -> dict:
    arms = load_arms()
    cells = load_all(Path("results/sweep"))
    if not arms:
        raise SystemExit("no arms in results/experiments — run scripts/run_experiments.py")

    out.mkdir(parents=True, exist_ok=True)
    (out / "charts").mkdir(exist_ok=True)
    for png in sorted(Path("results/charts").glob("*.png")):
        shutil.copy2(png, out / "charts" / png.name)

    with (out / "arms.jsonl").open("w", encoding="utf-8") as handle:
        for name in sorted(arms):
            handle.write(json.dumps(arms[name], default=str) + "\n")
    with (out / "cells.jsonl").open("w", encoding="utf-8") as handle:
        for cell in cells:
            handle.write(json.dumps(cell, default=str) + "\n")

    ending = select(cheap_bare=arms["A-baseline"], cheap_looped=arms["C-verified"],
                    frontier_bare=arms["D-reference"])
    provenance = {
        "measured_on": date.today().isoformat(),
        "models": _served(arms),
        "profile": "session (sweep) + all six arms (experiments)",
        "n_held_out": arms["A-baseline"]["n_items"],
        "account_tier": tier,
        "note": note,
        "ending": str(ending.ending),
        "arms_cost_usd": round(sum(a["cost_usd"]["value"] for a in arms.values()), 4),
        "sweep_cost_usd": round(sum(c["cost_usd"]["value"] for c in cells), 4),
        "arm_seconds": {n: a["seconds"] for n, a in sorted(arms.items())},
    }
    (out / "provenance.json").write_text(json.dumps(provenance, indent=2) + "\n")
    (out / "README.md").write_text(
        "# reference/\n\n"
        "**One full run, committed so you can see what this produces before spending "
        "anything.** Generated by `scripts/build_reference.py` from `results/` — never "
        "hand-edited, because a hand-maintained artefact is correct for about a week "
        "and then describes something else.\n\n"
        "Start with [`summary.md`](summary.md). [`provenance.json`](provenance.json) "
        "carries the date, the served models, the profile, the n and the account tier, "
        "because every figure here is one day on one account against one gold set and "
        "somebody will read it as what they should expect.\n\n"
        "| file | what it is |\n|---|---|\n"
        "| `summary.md` | every arm, its bands, its cost, and the named secondary's "
        "reading |\n"
        "| `provenance.json` | what this run was, in fields rather than prose |\n"
        "| `arms.jsonl` | the six arm summaries, one per line, with per-item outcomes |\n"
        "| `cells.jsonl` | the session sweep's four cells |\n"
        "| `charts/` | every figure, as rendered |\n\n"
        "## This is documentation, not a data source\n\n"
        "**No module under `src/loopeng/` may import anything here, and a test asserts "
        "it.** That is the structural difference from `results/reference/`, which was "
        "deleted: that directory was *loaded* by the renderer, so a stored measurement "
        "could reach a chart and be shown as a fresh one. Five mechanisms guarded "
        "against it — a hatched fill, a badge, a date on every row, a four-way mode "
        "flag and a test — and the guarding was the tell.\n\n"
        "The capability is gone rather than defended. A render path that cannot express "
        "\"stored\" cannot show one, and these files are unreachable from it.\n\n"
        "## Expect your numbers to differ\n\n"
        "Neither scoring model accepts a pinned temperature; both pin a seed, which the "
        "vendor documents as best-effort. Run-to-run movement is measured rather than "
        "assumed away — see `results/noise_floor_seeded.json`. Between the pilot and "
        "this run, one arm moved by two items and another crossed below the arm it is "
        "normally above. **That difference is the finding, not a fault.**\n",
        encoding="utf-8",
    )
    (out / "summary.md").write_text(
        f"# What one full run produced\n\n"
        f"**Measured {provenance['measured_on']}** · models "
        f"{', '.join(f'{r}={m}' for r, m in provenance['models'].items())} · "
        f"n={provenance['n_held_out']} held out · account tier: {tier}\n\n"
        f"{note}\n\n"
        f"{summary_table(arms, cells)}\n\n"
        f"## The named secondary\n\n```\n{ending.render()}\n```\n"
    )
    return provenance


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--note", required=True, help="What produced this run.")
    parser.add_argument("--tier", required=True, help="Account tier the timings reflect.")
    parser.add_argument("--out", type=Path, default=OUT)
    args = parser.parse_args(argv)

    provenance = build(args.note, args.tier, args.out)
    print(json.dumps(provenance, indent=2))
    print(f"\nwrote {args.out}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
